2022-11-22 19:16:19,750 INFO    StreamThr :37627 [internal.py:wandb_internal():88] W&B internal server running at pid: 37627, started at: 2022-11-22 19:16:19.749269
2022-11-22 19:16:19,753 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: status
2022-11-22 19:16:19,754 DEBUG   SenderThread:37627 [sender.py:send_request():317] send_request: status
2022-11-22 19:16:19,756 INFO    WriterThread:37627 [datastore.py:open_for_write():75] open: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/run-2vquv0w3.wandb
2022-11-22 19:16:19,756 DEBUG   SenderThread:37627 [sender.py:send():303] send: header
2022-11-22 19:16:19,756 DEBUG   SenderThread:37627 [sender.py:send():303] send: run
2022-11-22 19:16:19,776 INFO    SenderThread:37627 [sender.py:_maybe_setup_resume():593] checking resume status for None/YOLOR/2vquv0w3
2022-11-22 19:16:24,757 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:29,759 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:34,761 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:39,765 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:44,768 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:46,872 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: check_version
2022-11-22 19:16:46,876 INFO    SenderThread:37627 [dir_watcher.py:__init__():216] watching files in: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files
2022-11-22 19:16:46,877 INFO    SenderThread:37627 [sender.py:_start_run_threads():928] run started: 2vquv0w3 with start time 1669115779.746087
2022-11-22 19:16:46,877 DEBUG   SenderThread:37627 [sender.py:send():303] send: summary
2022-11-22 19:16:46,877 INFO    SenderThread:37627 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 19:16:46,878 DEBUG   SenderThread:37627 [sender.py:send_request():317] send_request: check_version
2022-11-22 19:16:47,879 INFO    Thread-17 :37627 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/wandb-summary.json
2022-11-22 19:16:47,920 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: run_start
2022-11-22 19:16:47,922 DEBUG   HandlerThread:37627 [system_info.py:__init__():31] System info init
2022-11-22 19:16:47,922 DEBUG   HandlerThread:37627 [system_info.py:__init__():46] System info init done
2022-11-22 19:16:47,922 INFO    HandlerThread:37627 [system_monitor.py:start():150] Starting system monitor
2022-11-22 19:16:47,922 INFO    SystemMonitor:37627 [system_monitor.py:_start():116] Starting system asset monitoring threads
2022-11-22 19:16:47,922 INFO    HandlerThread:37627 [system_monitor.py:probe():168] Collecting system info
2022-11-22 19:16:47,923 INFO    SystemMonitor:37627 [interfaces.py:start():168] Started cpu
2022-11-22 19:16:47,924 INFO    SystemMonitor:37627 [interfaces.py:start():168] Started disk
2022-11-22 19:16:47,925 INFO    SystemMonitor:37627 [interfaces.py:start():168] Started gpu
2022-11-22 19:16:47,927 INFO    SystemMonitor:37627 [interfaces.py:start():168] Started memory
2022-11-22 19:16:47,927 INFO    SystemMonitor:37627 [interfaces.py:start():168] Started network
2022-11-22 19:16:47,951 DEBUG   HandlerThread:37627 [system_info.py:probe():195] Probing system
2022-11-22 19:16:47,954 DEBUG   HandlerThread:37627 [git.py:repo():40] git repository is invalid
2022-11-22 19:16:47,954 DEBUG   HandlerThread:37627 [system_info.py:probe():241] Probing system done
2022-11-22 19:16:47,954 DEBUG   HandlerThread:37627 [system_monitor.py:probe():177] {'os': 'Linux-5.15.0-53-generic-x86_64-with-glibc2.17', 'python': '3.8.13', 'heartbeatAt': '2022-11-22T11:16:47.951102', 'startedAt': '2022-11-22T11:16:19.738685', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/rp/DeepLearning/yolov7-main/train.py', 'codePath': 'train.py', 'host': 'rp', 'username': 'rp', 'executable': '/home/rp/Softwares/anaconda3/envs/dyh/bin/python', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3218.7526875, 'min': 800.0, 'max': 4800.0}, 'cpu_freq_per_core': [{'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 4599.999, 'min': 800.0, 'max': 4800.0}, {'current': 4600.044, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 4600.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}], 'disk': {'total': 937.3305015563965, 'used': 300.8215751647949}, 'gpu': 'NVIDIA GeForce RTX 3080', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10497294336}], 'memory': {'total': 31.272598266601562}}
2022-11-22 19:16:47,955 INFO    HandlerThread:37627 [system_monitor.py:probe():178] Finished collecting system info
2022-11-22 19:16:47,955 INFO    HandlerThread:37627 [system_monitor.py:probe():181] Publishing system info
2022-11-22 19:16:47,955 DEBUG   HandlerThread:37627 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2022-11-22 19:16:47,956 DEBUG   HandlerThread:37627 [system_info.py:_save_pip():67] Saving pip packages done
2022-11-22 19:16:47,956 DEBUG   HandlerThread:37627 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2022-11-22 19:16:48,877 INFO    Thread-17 :37627 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/requirements.txt
2022-11-22 19:16:48,877 INFO    Thread-17 :37627 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/conda-environment.yaml
2022-11-22 19:16:50,432 DEBUG   HandlerThread:37627 [system_info.py:_save_conda():86] Saving conda packages done
2022-11-22 19:16:50,439 INFO    HandlerThread:37627 [system_monitor.py:probe():183] Finished publishing system info
2022-11-22 19:16:50,479 DEBUG   SenderThread:37627 [sender.py:send():303] send: files
2022-11-22 19:16:50,479 INFO    SenderThread:37627 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2022-11-22 19:16:50,490 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: stop_status
2022-11-22 19:16:50,490 DEBUG   SenderThread:37627 [sender.py:send_request():317] send_request: stop_status
2022-11-22 19:16:50,878 INFO    Thread-17 :37627 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/conda-environment.yaml
2022-11-22 19:16:50,878 INFO    Thread-17 :37627 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/wandb-metadata.json
2022-11-22 19:16:52,911 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: poll_exit
2022-11-22 19:16:56,228 DEBUG   SenderThread:37627 [sender.py:send():303] send: telemetry
2022-11-22 19:16:56,228 DEBUG   SenderThread:37627 [sender.py:send():303] send: telemetry
2022-11-22 19:16:56,228 DEBUG   SenderThread:37627 [sender.py:send():303] send: config
2022-11-22 19:16:56,229 DEBUG   SenderThread:37627 [sender.py:send():303] send: config
2022-11-22 19:16:56,234 DEBUG   SenderThread:37627 [sender.py:send():303] send: exit
2022-11-22 19:16:56,234 INFO    SenderThread:37627 [sender.py:send_exit():442] handling exit code: 0
2022-11-22 19:16:56,234 INFO    SenderThread:37627 [sender.py:send_exit():444] handling runtime: 3
2022-11-22 19:16:56,234 INFO    SenderThread:37627 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 19:16:56,235 INFO    SenderThread:37627 [sender.py:send_exit():450] send defer
2022-11-22 19:16:56,235 DEBUG   SenderThread:37627 [sender.py:send_request():317] send_request: poll_exit
2022-11-22 19:16:56,235 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:56,235 INFO    HandlerThread:37627 [handler.py:handle_request_defer():162] handle defer: 0
2022-11-22 19:16:56,236 DEBUG   SenderThread:37627 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:56,236 INFO    SenderThread:37627 [sender.py:send_request_defer():459] handle sender defer: 0
2022-11-22 19:16:56,236 INFO    SenderThread:37627 [sender.py:transition_state():463] send defer: 1
2022-11-22 19:16:56,236 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:56,236 INFO    HandlerThread:37627 [handler.py:handle_request_defer():162] handle defer: 1
2022-11-22 19:16:56,237 INFO    HandlerThread:37627 [system_monitor.py:finish():160] Stopping system monitor
2022-11-22 19:16:56,237 DEBUG   SystemMonitor:37627 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2022-11-22 19:16:56,238 DEBUG   SystemMonitor:37627 [system_monitor.py:_start():137] Finished system metrics aggregation loop
2022-11-22 19:16:56,238 DEBUG   SystemMonitor:37627 [system_monitor.py:_start():141] Publishing last batch of metrics
2022-11-22 19:16:56,239 INFO    HandlerThread:37627 [interfaces.py:finish():173] Joined cpu
2022-11-22 19:16:56,239 INFO    HandlerThread:37627 [interfaces.py:finish():173] Joined disk
2022-11-22 19:16:56,284 INFO    HandlerThread:37627 [interfaces.py:finish():173] Joined gpu
2022-11-22 19:16:56,284 INFO    HandlerThread:37627 [interfaces.py:finish():173] Joined memory
2022-11-22 19:16:56,285 INFO    HandlerThread:37627 [interfaces.py:finish():173] Joined network
2022-11-22 19:16:56,285 DEBUG   SenderThread:37627 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:56,285 INFO    SenderThread:37627 [sender.py:send_request_defer():459] handle sender defer: 1
2022-11-22 19:16:56,285 INFO    SenderThread:37627 [sender.py:transition_state():463] send defer: 2
2022-11-22 19:16:56,285 DEBUG   SenderThread:37627 [sender.py:send():303] send: stats
2022-11-22 19:16:56,286 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:56,286 INFO    HandlerThread:37627 [handler.py:handle_request_defer():162] handle defer: 2
2022-11-22 19:16:56,286 DEBUG   SenderThread:37627 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:56,286 INFO    SenderThread:37627 [sender.py:send_request_defer():459] handle sender defer: 2
2022-11-22 19:16:56,286 INFO    SenderThread:37627 [sender.py:transition_state():463] send defer: 3
2022-11-22 19:16:56,286 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:56,287 INFO    HandlerThread:37627 [handler.py:handle_request_defer():162] handle defer: 3
2022-11-22 19:16:56,287 DEBUG   SenderThread:37627 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:56,287 INFO    SenderThread:37627 [sender.py:send_request_defer():459] handle sender defer: 3
2022-11-22 19:16:56,287 INFO    SenderThread:37627 [sender.py:transition_state():463] send defer: 4
2022-11-22 19:16:56,287 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:56,287 INFO    HandlerThread:37627 [handler.py:handle_request_defer():162] handle defer: 4
2022-11-22 19:16:56,287 DEBUG   SenderThread:37627 [sender.py:send():303] send: summary
2022-11-22 19:16:56,288 INFO    SenderThread:37627 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 19:16:56,288 DEBUG   SenderThread:37627 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:56,288 INFO    SenderThread:37627 [sender.py:send_request_defer():459] handle sender defer: 4
2022-11-22 19:16:56,288 INFO    SenderThread:37627 [sender.py:transition_state():463] send defer: 5
2022-11-22 19:16:56,288 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:16:56,288 INFO    HandlerThread:37627 [handler.py:handle_request_defer():162] handle defer: 5
2022-11-22 19:16:56,289 DEBUG   SenderThread:37627 [sender.py:send_request():317] send_request: defer
2022-11-22 19:16:56,289 INFO    SenderThread:37627 [sender.py:send_request_defer():459] handle sender defer: 5
2022-11-22 19:16:56,883 INFO    Thread-17 :37627 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/wandb-summary.json
2022-11-22 19:16:56,884 INFO    Thread-17 :37627 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/output.log
2022-11-22 19:16:57,914 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:58,887 INFO    Thread-17 :37627 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/output.log
2022-11-22 19:17:02,009 INFO    SenderThread:37627 [sender.py:transition_state():463] send defer: 6
2022-11-22 19:17:02,010 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:17:02,010 INFO    HandlerThread:37627 [handler.py:handle_request_defer():162] handle defer: 6
2022-11-22 19:17:02,010 DEBUG   SenderThread:37627 [sender.py:send_request():317] send_request: defer
2022-11-22 19:17:02,010 INFO    SenderThread:37627 [sender.py:send_request_defer():459] handle sender defer: 6
2022-11-22 19:17:02,355 INFO    SenderThread:37627 [sender.py:transition_state():463] send defer: 7
2022-11-22 19:17:02,356 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:17:02,357 INFO    HandlerThread:37627 [handler.py:handle_request_defer():162] handle defer: 7
2022-11-22 19:17:02,358 DEBUG   SenderThread:37627 [sender.py:send_request():317] send_request: defer
2022-11-22 19:17:02,358 INFO    SenderThread:37627 [sender.py:send_request_defer():459] handle sender defer: 7
2022-11-22 19:17:02,359 INFO    SenderThread:37627 [dir_watcher.py:finish():362] shutting down directory watcher
2022-11-22 19:17:02,892 INFO    SenderThread:37627 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/output.log
2022-11-22 19:17:02,893 INFO    SenderThread:37627 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/config.yaml
2022-11-22 19:17:02,896 INFO    SenderThread:37627 [dir_watcher.py:finish():392] scan: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files
2022-11-22 19:17:02,897 INFO    SenderThread:37627 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/wandb-summary.json wandb-summary.json
2022-11-22 19:17:02,898 INFO    SenderThread:37627 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/config.yaml config.yaml
2022-11-22 19:17:02,899 INFO    SenderThread:37627 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/output.log output.log
2022-11-22 19:17:02,900 INFO    SenderThread:37627 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/requirements.txt requirements.txt
2022-11-22 19:17:02,900 INFO    SenderThread:37627 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/conda-environment.yaml conda-environment.yaml
2022-11-22 19:17:02,908 INFO    SenderThread:37627 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/wandb-metadata.json wandb-metadata.json
2022-11-22 19:17:02,914 INFO    SenderThread:37627 [sender.py:transition_state():463] send defer: 8
2022-11-22 19:17:02,948 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:02,954 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:17:02,954 INFO    HandlerThread:37627 [handler.py:handle_request_defer():162] handle defer: 8
2022-11-22 19:17:02,961 DEBUG   SenderThread:37627 [sender.py:send_request():317] send_request: defer
2022-11-22 19:17:02,966 INFO    SenderThread:37627 [sender.py:send_request_defer():459] handle sender defer: 8
2022-11-22 19:17:02,966 INFO    SenderThread:37627 [file_pusher.py:finish():168] shutting down file pusher
2022-11-22 19:17:07,932 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:12,935 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:15,934 ERROR   Thread-20 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=XRIPYmr530ARZ%2FvBYkXAOBG4dFq9NZeVIrfmKyU9AwiHqgftZy4%2BmmRcQMi9d8vgN9iMxKduyPnJ0dmbP6%2FV4Zbmkk5bil%2F%2BTsZByPzK%2Fbcy3mS0M%2FhzmewozRvPB8vsaYOIKTSM8EfQD3srcuiJ%2FY6ZnYnfkFNt5h1ricxTwCTd%2FBcPoQfmDvQUScEBCMidQJ9NlNr5wI%2BPWobY6p83gaXuiuxzClWRkUHoEpPZkSkJkMmRxcMomcahDJOrebXfXLHI8ixY3vj%2B6qEHDZn5zGXr9TWq2xQW5qRGg4XoA%2BntWWk%2FcwQMytYllbqli7sYMj9CBmpff9FAc3WX%2FZotvA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=XRIPYmr530ARZ%2FvBYkXAOBG4dFq9NZeVIrfmKyU9AwiHqgftZy4%2BmmRcQMi9d8vgN9iMxKduyPnJ0dmbP6%2FV4Zbmkk5bil%2F%2BTsZByPzK%2Fbcy3mS0M%2FhzmewozRvPB8vsaYOIKTSM8EfQD3srcuiJ%2FY6ZnYnfkFNt5h1ricxTwCTd%2FBcPoQfmDvQUScEBCMidQJ9NlNr5wI%2BPWobY6p83gaXuiuxzClWRkUHoEpPZkSkJkMmRxcMomcahDJOrebXfXLHI8ixY3vj%2B6qEHDZn5zGXr9TWq2xQW5qRGg4XoA%2BntWWk%2FcwQMytYllbqli7sYMj9CBmpff9FAc3WX%2FZotvA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f0824cd00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:15,935 ERROR   Thread-20 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2654'}
2022-11-22 19:17:15,935 ERROR   Thread-20 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:17,939 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:22,944 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:27,151 ERROR   Thread-20 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=XRIPYmr530ARZ%2FvBYkXAOBG4dFq9NZeVIrfmKyU9AwiHqgftZy4%2BmmRcQMi9d8vgN9iMxKduyPnJ0dmbP6%2FV4Zbmkk5bil%2F%2BTsZByPzK%2Fbcy3mS0M%2FhzmewozRvPB8vsaYOIKTSM8EfQD3srcuiJ%2FY6ZnYnfkFNt5h1ricxTwCTd%2FBcPoQfmDvQUScEBCMidQJ9NlNr5wI%2BPWobY6p83gaXuiuxzClWRkUHoEpPZkSkJkMmRxcMomcahDJOrebXfXLHI8ixY3vj%2B6qEHDZn5zGXr9TWq2xQW5qRGg4XoA%2BntWWk%2FcwQMytYllbqli7sYMj9CBmpff9FAc3WX%2FZotvA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=XRIPYmr530ARZ%2FvBYkXAOBG4dFq9NZeVIrfmKyU9AwiHqgftZy4%2BmmRcQMi9d8vgN9iMxKduyPnJ0dmbP6%2FV4Zbmkk5bil%2F%2BTsZByPzK%2Fbcy3mS0M%2FhzmewozRvPB8vsaYOIKTSM8EfQD3srcuiJ%2FY6ZnYnfkFNt5h1ricxTwCTd%2FBcPoQfmDvQUScEBCMidQJ9NlNr5wI%2BPWobY6p83gaXuiuxzClWRkUHoEpPZkSkJkMmRxcMomcahDJOrebXfXLHI8ixY3vj%2B6qEHDZn5zGXr9TWq2xQW5qRGg4XoA%2BntWWk%2FcwQMytYllbqli7sYMj9CBmpff9FAc3WX%2FZotvA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f08245640>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:27,152 ERROR   Thread-20 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2654'}
2022-11-22 19:17:27,152 ERROR   Thread-20 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:27,946 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:28,392 ERROR   Thread-24 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/requirements.txt?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=XIyBSteAGGYwrXBGu0yF%2F0oViBmKrjM45LEfCNC28z3dLBNDGgj0fwC6NvaEFtM3SE5X%2FSPrzp8jLREOPG%2FVsIhCzjHD1k%2BB%2FGherkP2vwecPEN04PWYtLXWju6jsKHW3dPJiNcLFIRyKcw0jemxcC%2B2V7cONQMi6eRegZlWV2Iunp67MMoUUMmZZC7k7SPcF1yOziMeWRbzm159yzYMzm9%2BzsxisTOb7sZCpMuIcAL991hHA2wEvJKk0Lm979%2Fhqta1Hcu3BmOUq24ujDbnNlKxzRr87fBDYcg2FqShGCRyeBi7EDJeFSVy4iHKBioJwutESdBKMxRviRPEi1voKg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/requirements.txt?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=XIyBSteAGGYwrXBGu0yF%2F0oViBmKrjM45LEfCNC28z3dLBNDGgj0fwC6NvaEFtM3SE5X%2FSPrzp8jLREOPG%2FVsIhCzjHD1k%2BB%2FGherkP2vwecPEN04PWYtLXWju6jsKHW3dPJiNcLFIRyKcw0jemxcC%2B2V7cONQMi6eRegZlWV2Iunp67MMoUUMmZZC7k7SPcF1yOziMeWRbzm159yzYMzm9%2BzsxisTOb7sZCpMuIcAL991hHA2wEvJKk0Lm979%2Fhqta1Hcu3BmOUq24ujDbnNlKxzRr87fBDYcg2FqShGCRyeBi7EDJeFSVy4iHKBioJwutESdBKMxRviRPEi1voKg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f0846feb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:28,393 ERROR   Thread-24 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:17:28,393 ERROR   Thread-24 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:28,399 ERROR   Thread-21 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/wandb-summary.json?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=iYCyYkFRl%2Fkr6GuehXN406%2Fuy8%2BlboWrpBQnfOFV6oPk0bxAhcM57la70MLIdZ%2BROhD8%2F5eFp%2BlBQAkFdOlELMWSZzkgN4oeBZ1xHYhZgfyFUUv5LVW3MTsVrcAwlrQl48ge7YpB0iddOiEDVvwWinmb7PZDHAXnWa2V6U3XRzDfg42qzUonaSTdYn4ZkRloSzqbgf%2Bz4P5JJ9FlXZgZ2NXO4F3sb8sW6%2Bq4LkGMDwLbRvkLfBSBREFxHVOevMMQC87fy6PmpBx6pzmSJzXamysMhwpnG5rKhk6Em0QowEEhyvnrSoLpLyZX3EwpJogKEmOl7LxSlNQbIjZ5md8qJg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/wandb-summary.json?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=iYCyYkFRl%2Fkr6GuehXN406%2Fuy8%2BlboWrpBQnfOFV6oPk0bxAhcM57la70MLIdZ%2BROhD8%2F5eFp%2BlBQAkFdOlELMWSZzkgN4oeBZ1xHYhZgfyFUUv5LVW3MTsVrcAwlrQl48ge7YpB0iddOiEDVvwWinmb7PZDHAXnWa2V6U3XRzDfg42qzUonaSTdYn4ZkRloSzqbgf%2Bz4P5JJ9FlXZgZ2NXO4F3sb8sW6%2Bq4LkGMDwLbRvkLfBSBREFxHVOevMMQC87fy6PmpBx6pzmSJzXamysMhwpnG5rKhk6Em0QowEEhyvnrSoLpLyZX3EwpJogKEmOl7LxSlNQbIjZ5md8qJg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f083ce070>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:28,400 ERROR   Thread-21 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:17:28,400 ERROR   Thread-21 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:28,406 ERROR   Thread-23 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/output.log?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SZzza2fAtlwGylqzsUqLBUPJ1vf3SgsmVFPxyYEnNbu6ASOmywdMmqSjXBpv%2Be9D04pfJ%2FxO8oJ2QnONhS53WjvjJjL46CT%2F0Q8XhzXTtaosHeKDpcpu%2F%2BrjxUtWPxvRUdFPWGFEW8Y8F6nwJBELWLsETaU4c8GUG49t89e2Mjv1RsHITTjfSLChX9Lr76jdH4kBvINhQNk5Tz5H%2FfCpB3V5kZupAPhUQQ1NevStOmJD5D4%2Bbh4RYSgqzwtuCvFEUbXqtNY7AFrS2wdF9FE0B2XmBn%2FNK%2BYWDUOGYiMWpaQv4gsL9Vxlzuv24wCYbEAitBKwqQq8c0hFrO7h3bDDuQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/output.log?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SZzza2fAtlwGylqzsUqLBUPJ1vf3SgsmVFPxyYEnNbu6ASOmywdMmqSjXBpv%2Be9D04pfJ%2FxO8oJ2QnONhS53WjvjJjL46CT%2F0Q8XhzXTtaosHeKDpcpu%2F%2BrjxUtWPxvRUdFPWGFEW8Y8F6nwJBELWLsETaU4c8GUG49t89e2Mjv1RsHITTjfSLChX9Lr76jdH4kBvINhQNk5Tz5H%2FfCpB3V5kZupAPhUQQ1NevStOmJD5D4%2Bbh4RYSgqzwtuCvFEUbXqtNY7AFrS2wdF9FE0B2XmBn%2FNK%2BYWDUOGYiMWpaQv4gsL9Vxlzuv24wCYbEAitBKwqQq8c0hFrO7h3bDDuQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f083ce430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:28,407 ERROR   Thread-23 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11206'}
2022-11-22 19:17:28,407 ERROR   Thread-23 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:28,695 ERROR   Thread-22 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/config.yaml?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=H6amYcwHvij6ZBShcIOmMB4ccq4RXMHCp%2FsY9QQrhy%2FlhtPOVpFzTpBO5b99eL62As1%2BimvhKnzk8Vr2V%2FQJldGdNW1mu0%2BSUGZiN3trhuG5E916Ks8L0BtXWWFwF0rCLT7YqPvM1DxH%2FS9Pt9OVRZxPI57mMnIpk6ND0fLLBjSb%2BngcGtWlNsOhA5%2FfFoFpnCDqnFS9s6HoPO7H70G1nDtPqXfuzXXO2ZQ665Sg5Z3Zq5a%2BWuoDd7Ym2XPJD%2BKaYTWiis6osl6TWZPfVrjOUs4e1HWYF5P5Z2WJMNBVclzu2yMu%2FrM8ctYyaXit8ywUCD6VftuHeQ0e71OMYdA0HQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/config.yaml?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=H6amYcwHvij6ZBShcIOmMB4ccq4RXMHCp%2FsY9QQrhy%2FlhtPOVpFzTpBO5b99eL62As1%2BimvhKnzk8Vr2V%2FQJldGdNW1mu0%2BSUGZiN3trhuG5E916Ks8L0BtXWWFwF0rCLT7YqPvM1DxH%2FS9Pt9OVRZxPI57mMnIpk6ND0fLLBjSb%2BngcGtWlNsOhA5%2FfFoFpnCDqnFS9s6HoPO7H70G1nDtPqXfuzXXO2ZQ665Sg5Z3Zq5a%2BWuoDd7Ym2XPJD%2BKaYTWiis6osl6TWZPfVrjOUs4e1HWYF5P5Z2WJMNBVclzu2yMu%2FrM8ctYyaXit8ywUCD6VftuHeQ0e71OMYdA0HQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f083ce130>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:28,696 ERROR   Thread-22 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:17:28,696 ERROR   Thread-22 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:32,949 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:33,102 ERROR   Thread-25 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/conda-environment.yaml?Expires=1669202242&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=FR0ph17H34SZtLAp3XnK8NVTiqz8bn5q%2BrAVJvTYVzl5wxUX8Os19ox0lrl4mqIaOwFsEBcr8kKda6aW2ospktQ6AbCYV5lzE%2BL7zTnJ8paIzqTD8n0ZQPNkYr1br3F2UCK61nbb9aa9MUa%2BCQDrd4%2FHjXXEe%2B4yVW3JvYK%2Fat0bJ6NgtRrg15lx79JTwljAaJqrFX2FVvv2jm5Zxizf%2B5hpBXax7RWFoqMXSYODQNbG%2FsH%2BqiyaeaytB4CdJn1jT376pmpwvh18SmMJWbSFxrCpNWpOAYNgNY0x3FmPQ5s292hNmU86IYh5rhemGhCOB1qsh%2FchSHSGD5ESz2n80g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/conda-environment.yaml?Expires=1669202242&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=FR0ph17H34SZtLAp3XnK8NVTiqz8bn5q%2BrAVJvTYVzl5wxUX8Os19ox0lrl4mqIaOwFsEBcr8kKda6aW2ospktQ6AbCYV5lzE%2BL7zTnJ8paIzqTD8n0ZQPNkYr1br3F2UCK61nbb9aa9MUa%2BCQDrd4%2FHjXXEe%2B4yVW3JvYK%2Fat0bJ6NgtRrg15lx79JTwljAaJqrFX2FVvv2jm5Zxizf%2B5hpBXax7RWFoqMXSYODQNbG%2FsH%2BqiyaeaytB4CdJn1jT376pmpwvh18SmMJWbSFxrCpNWpOAYNgNY0x3FmPQ5s292hNmU86IYh5rhemGhCOB1qsh%2FchSHSGD5ESz2n80g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f083eeca0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:33,102 ERROR   Thread-25 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:17:33,102 ERROR   Thread-25 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:37,952 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:39,274 ERROR   Thread-20 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=XRIPYmr530ARZ%2FvBYkXAOBG4dFq9NZeVIrfmKyU9AwiHqgftZy4%2BmmRcQMi9d8vgN9iMxKduyPnJ0dmbP6%2FV4Zbmkk5bil%2F%2BTsZByPzK%2Fbcy3mS0M%2FhzmewozRvPB8vsaYOIKTSM8EfQD3srcuiJ%2FY6ZnYnfkFNt5h1ricxTwCTd%2FBcPoQfmDvQUScEBCMidQJ9NlNr5wI%2BPWobY6p83gaXuiuxzClWRkUHoEpPZkSkJkMmRxcMomcahDJOrebXfXLHI8ixY3vj%2B6qEHDZn5zGXr9TWq2xQW5qRGg4XoA%2BntWWk%2FcwQMytYllbqli7sYMj9CBmpff9FAc3WX%2FZotvA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=XRIPYmr530ARZ%2FvBYkXAOBG4dFq9NZeVIrfmKyU9AwiHqgftZy4%2BmmRcQMi9d8vgN9iMxKduyPnJ0dmbP6%2FV4Zbmkk5bil%2F%2BTsZByPzK%2Fbcy3mS0M%2FhzmewozRvPB8vsaYOIKTSM8EfQD3srcuiJ%2FY6ZnYnfkFNt5h1ricxTwCTd%2FBcPoQfmDvQUScEBCMidQJ9NlNr5wI%2BPWobY6p83gaXuiuxzClWRkUHoEpPZkSkJkMmRxcMomcahDJOrebXfXLHI8ixY3vj%2B6qEHDZn5zGXr9TWq2xQW5qRGg4XoA%2BntWWk%2FcwQMytYllbqli7sYMj9CBmpff9FAc3WX%2FZotvA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f085f0cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:39,274 ERROR   Thread-20 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2654'}
2022-11-22 19:17:39,274 ERROR   Thread-20 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:39,484 ERROR   Thread-21 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/wandb-summary.json?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=iYCyYkFRl%2Fkr6GuehXN406%2Fuy8%2BlboWrpBQnfOFV6oPk0bxAhcM57la70MLIdZ%2BROhD8%2F5eFp%2BlBQAkFdOlELMWSZzkgN4oeBZ1xHYhZgfyFUUv5LVW3MTsVrcAwlrQl48ge7YpB0iddOiEDVvwWinmb7PZDHAXnWa2V6U3XRzDfg42qzUonaSTdYn4ZkRloSzqbgf%2Bz4P5JJ9FlXZgZ2NXO4F3sb8sW6%2Bq4LkGMDwLbRvkLfBSBREFxHVOevMMQC87fy6PmpBx6pzmSJzXamysMhwpnG5rKhk6Em0QowEEhyvnrSoLpLyZX3EwpJogKEmOl7LxSlNQbIjZ5md8qJg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/wandb-summary.json?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=iYCyYkFRl%2Fkr6GuehXN406%2Fuy8%2BlboWrpBQnfOFV6oPk0bxAhcM57la70MLIdZ%2BROhD8%2F5eFp%2BlBQAkFdOlELMWSZzkgN4oeBZ1xHYhZgfyFUUv5LVW3MTsVrcAwlrQl48ge7YpB0iddOiEDVvwWinmb7PZDHAXnWa2V6U3XRzDfg42qzUonaSTdYn4ZkRloSzqbgf%2Bz4P5JJ9FlXZgZ2NXO4F3sb8sW6%2Bq4LkGMDwLbRvkLfBSBREFxHVOevMMQC87fy6PmpBx6pzmSJzXamysMhwpnG5rKhk6Em0QowEEhyvnrSoLpLyZX3EwpJogKEmOl7LxSlNQbIjZ5md8qJg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f0825c310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:39,485 ERROR   Thread-21 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:17:39,486 ERROR   Thread-21 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:39,517 ERROR   Thread-24 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/requirements.txt?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=XIyBSteAGGYwrXBGu0yF%2F0oViBmKrjM45LEfCNC28z3dLBNDGgj0fwC6NvaEFtM3SE5X%2FSPrzp8jLREOPG%2FVsIhCzjHD1k%2BB%2FGherkP2vwecPEN04PWYtLXWju6jsKHW3dPJiNcLFIRyKcw0jemxcC%2B2V7cONQMi6eRegZlWV2Iunp67MMoUUMmZZC7k7SPcF1yOziMeWRbzm159yzYMzm9%2BzsxisTOb7sZCpMuIcAL991hHA2wEvJKk0Lm979%2Fhqta1Hcu3BmOUq24ujDbnNlKxzRr87fBDYcg2FqShGCRyeBi7EDJeFSVy4iHKBioJwutESdBKMxRviRPEi1voKg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/requirements.txt?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=XIyBSteAGGYwrXBGu0yF%2F0oViBmKrjM45LEfCNC28z3dLBNDGgj0fwC6NvaEFtM3SE5X%2FSPrzp8jLREOPG%2FVsIhCzjHD1k%2BB%2FGherkP2vwecPEN04PWYtLXWju6jsKHW3dPJiNcLFIRyKcw0jemxcC%2B2V7cONQMi6eRegZlWV2Iunp67MMoUUMmZZC7k7SPcF1yOziMeWRbzm159yzYMzm9%2BzsxisTOb7sZCpMuIcAL991hHA2wEvJKk0Lm979%2Fhqta1Hcu3BmOUq24ujDbnNlKxzRr87fBDYcg2FqShGCRyeBi7EDJeFSVy4iHKBioJwutESdBKMxRviRPEi1voKg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f0824d430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:39,518 ERROR   Thread-24 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:17:39,518 ERROR   Thread-24 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:39,594 ERROR   Thread-23 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/output.log?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SZzza2fAtlwGylqzsUqLBUPJ1vf3SgsmVFPxyYEnNbu6ASOmywdMmqSjXBpv%2Be9D04pfJ%2FxO8oJ2QnONhS53WjvjJjL46CT%2F0Q8XhzXTtaosHeKDpcpu%2F%2BrjxUtWPxvRUdFPWGFEW8Y8F6nwJBELWLsETaU4c8GUG49t89e2Mjv1RsHITTjfSLChX9Lr76jdH4kBvINhQNk5Tz5H%2FfCpB3V5kZupAPhUQQ1NevStOmJD5D4%2Bbh4RYSgqzwtuCvFEUbXqtNY7AFrS2wdF9FE0B2XmBn%2FNK%2BYWDUOGYiMWpaQv4gsL9Vxlzuv24wCYbEAitBKwqQq8c0hFrO7h3bDDuQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/output.log?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SZzza2fAtlwGylqzsUqLBUPJ1vf3SgsmVFPxyYEnNbu6ASOmywdMmqSjXBpv%2Be9D04pfJ%2FxO8oJ2QnONhS53WjvjJjL46CT%2F0Q8XhzXTtaosHeKDpcpu%2F%2BrjxUtWPxvRUdFPWGFEW8Y8F6nwJBELWLsETaU4c8GUG49t89e2Mjv1RsHITTjfSLChX9Lr76jdH4kBvINhQNk5Tz5H%2FfCpB3V5kZupAPhUQQ1NevStOmJD5D4%2Bbh4RYSgqzwtuCvFEUbXqtNY7AFrS2wdF9FE0B2XmBn%2FNK%2BYWDUOGYiMWpaQv4gsL9Vxlzuv24wCYbEAitBKwqQq8c0hFrO7h3bDDuQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f083ce130>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:39,595 ERROR   Thread-23 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11206'}
2022-11-22 19:17:39,595 ERROR   Thread-23 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:39,799 ERROR   Thread-22 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/config.yaml?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=H6amYcwHvij6ZBShcIOmMB4ccq4RXMHCp%2FsY9QQrhy%2FlhtPOVpFzTpBO5b99eL62As1%2BimvhKnzk8Vr2V%2FQJldGdNW1mu0%2BSUGZiN3trhuG5E916Ks8L0BtXWWFwF0rCLT7YqPvM1DxH%2FS9Pt9OVRZxPI57mMnIpk6ND0fLLBjSb%2BngcGtWlNsOhA5%2FfFoFpnCDqnFS9s6HoPO7H70G1nDtPqXfuzXXO2ZQ665Sg5Z3Zq5a%2BWuoDd7Ym2XPJD%2BKaYTWiis6osl6TWZPfVrjOUs4e1HWYF5P5Z2WJMNBVclzu2yMu%2FrM8ctYyaXit8ywUCD6VftuHeQ0e71OMYdA0HQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/config.yaml?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=H6amYcwHvij6ZBShcIOmMB4ccq4RXMHCp%2FsY9QQrhy%2FlhtPOVpFzTpBO5b99eL62As1%2BimvhKnzk8Vr2V%2FQJldGdNW1mu0%2BSUGZiN3trhuG5E916Ks8L0BtXWWFwF0rCLT7YqPvM1DxH%2FS9Pt9OVRZxPI57mMnIpk6ND0fLLBjSb%2BngcGtWlNsOhA5%2FfFoFpnCDqnFS9s6HoPO7H70G1nDtPqXfuzXXO2ZQ665Sg5Z3Zq5a%2BWuoDd7Ym2XPJD%2BKaYTWiis6osl6TWZPfVrjOUs4e1HWYF5P5Z2WJMNBVclzu2yMu%2FrM8ctYyaXit8ywUCD6VftuHeQ0e71OMYdA0HQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f083ce580>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:39,799 ERROR   Thread-22 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:17:39,799 ERROR   Thread-22 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:42,955 DEBUG   HandlerThread:37627 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:17:44,347 ERROR   Thread-25 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/conda-environment.yaml?Expires=1669202242&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=FR0ph17H34SZtLAp3XnK8NVTiqz8bn5q%2BrAVJvTYVzl5wxUX8Os19ox0lrl4mqIaOwFsEBcr8kKda6aW2ospktQ6AbCYV5lzE%2BL7zTnJ8paIzqTD8n0ZQPNkYr1br3F2UCK61nbb9aa9MUa%2BCQDrd4%2FHjXXEe%2B4yVW3JvYK%2Fat0bJ6NgtRrg15lx79JTwljAaJqrFX2FVvv2jm5Zxizf%2B5hpBXax7RWFoqMXSYODQNbG%2FsH%2BqiyaeaytB4CdJn1jT376pmpwvh18SmMJWbSFxrCpNWpOAYNgNY0x3FmPQ5s292hNmU86IYh5rhemGhCOB1qsh%2FchSHSGD5ESz2n80g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/conda-environment.yaml?Expires=1669202242&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=FR0ph17H34SZtLAp3XnK8NVTiqz8bn5q%2BrAVJvTYVzl5wxUX8Os19ox0lrl4mqIaOwFsEBcr8kKda6aW2ospktQ6AbCYV5lzE%2BL7zTnJ8paIzqTD8n0ZQPNkYr1br3F2UCK61nbb9aa9MUa%2BCQDrd4%2FHjXXEe%2B4yVW3JvYK%2Fat0bJ6NgtRrg15lx79JTwljAaJqrFX2FVvv2jm5Zxizf%2B5hpBXax7RWFoqMXSYODQNbG%2FsH%2BqiyaeaytB4CdJn1jT376pmpwvh18SmMJWbSFxrCpNWpOAYNgNY0x3FmPQ5s292hNmU86IYh5rhemGhCOB1qsh%2FchSHSGD5ESz2n80g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f0825c580>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:44,347 ERROR   Thread-25 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:17:44,348 ERROR   Thread-25 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:48,851 WARNING StreamThr :37627 [internal.py:is_dead():385] Internal process exiting, parent pid 37527 disappeared
2022-11-22 19:17:48,851 ERROR   StreamThr :37627 [internal.py:wandb_internal():147] Internal process shutdown.
2022-11-22 19:17:48,962 INFO    HandlerThread:37627 [handler.py:finish():814] shutting down handler
2022-11-22 19:17:48,976 INFO    SenderThread:37627 [sender.py:finish():1331] shutting down sender
2022-11-22 19:17:48,976 INFO    SenderThread:37627 [file_pusher.py:finish():168] shutting down file pusher
2022-11-22 19:17:48,976 INFO    SenderThread:37627 [file_pusher.py:join():173] waiting for file pusher
2022-11-22 19:17:49,329 INFO    WriterThread:37627 [datastore.py:close():279] close: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/run-2vquv0w3.wandb
2022-11-22 19:17:51,673 ERROR   Thread-24 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/requirements.txt?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=XIyBSteAGGYwrXBGu0yF%2F0oViBmKrjM45LEfCNC28z3dLBNDGgj0fwC6NvaEFtM3SE5X%2FSPrzp8jLREOPG%2FVsIhCzjHD1k%2BB%2FGherkP2vwecPEN04PWYtLXWju6jsKHW3dPJiNcLFIRyKcw0jemxcC%2B2V7cONQMi6eRegZlWV2Iunp67MMoUUMmZZC7k7SPcF1yOziMeWRbzm159yzYMzm9%2BzsxisTOb7sZCpMuIcAL991hHA2wEvJKk0Lm979%2Fhqta1Hcu3BmOUq24ujDbnNlKxzRr87fBDYcg2FqShGCRyeBi7EDJeFSVy4iHKBioJwutESdBKMxRviRPEi1voKg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/requirements.txt?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=XIyBSteAGGYwrXBGu0yF%2F0oViBmKrjM45LEfCNC28z3dLBNDGgj0fwC6NvaEFtM3SE5X%2FSPrzp8jLREOPG%2FVsIhCzjHD1k%2BB%2FGherkP2vwecPEN04PWYtLXWju6jsKHW3dPJiNcLFIRyKcw0jemxcC%2B2V7cONQMi6eRegZlWV2Iunp67MMoUUMmZZC7k7SPcF1yOziMeWRbzm159yzYMzm9%2BzsxisTOb7sZCpMuIcAL991hHA2wEvJKk0Lm979%2Fhqta1Hcu3BmOUq24ujDbnNlKxzRr87fBDYcg2FqShGCRyeBi7EDJeFSVy4iHKBioJwutESdBKMxRviRPEi1voKg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f083b0be0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:51,673 ERROR   Thread-24 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:17:51,673 ERROR   Thread-24 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:51,751 ERROR   Thread-23 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/output.log?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SZzza2fAtlwGylqzsUqLBUPJ1vf3SgsmVFPxyYEnNbu6ASOmywdMmqSjXBpv%2Be9D04pfJ%2FxO8oJ2QnONhS53WjvjJjL46CT%2F0Q8XhzXTtaosHeKDpcpu%2F%2BrjxUtWPxvRUdFPWGFEW8Y8F6nwJBELWLsETaU4c8GUG49t89e2Mjv1RsHITTjfSLChX9Lr76jdH4kBvINhQNk5Tz5H%2FfCpB3V5kZupAPhUQQ1NevStOmJD5D4%2Bbh4RYSgqzwtuCvFEUbXqtNY7AFrS2wdF9FE0B2XmBn%2FNK%2BYWDUOGYiMWpaQv4gsL9Vxlzuv24wCYbEAitBKwqQq8c0hFrO7h3bDDuQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/output.log?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SZzza2fAtlwGylqzsUqLBUPJ1vf3SgsmVFPxyYEnNbu6ASOmywdMmqSjXBpv%2Be9D04pfJ%2FxO8oJ2QnONhS53WjvjJjL46CT%2F0Q8XhzXTtaosHeKDpcpu%2F%2BrjxUtWPxvRUdFPWGFEW8Y8F6nwJBELWLsETaU4c8GUG49t89e2Mjv1RsHITTjfSLChX9Lr76jdH4kBvINhQNk5Tz5H%2FfCpB3V5kZupAPhUQQ1NevStOmJD5D4%2Bbh4RYSgqzwtuCvFEUbXqtNY7AFrS2wdF9FE0B2XmBn%2FNK%2BYWDUOGYiMWpaQv4gsL9Vxlzuv24wCYbEAitBKwqQq8c0hFrO7h3bDDuQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f0846f280>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:51,751 ERROR   Thread-23 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11206'}
2022-11-22 19:17:51,751 ERROR   Thread-23 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:51,847 ERROR   Thread-21 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/wandb-summary.json?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=iYCyYkFRl%2Fkr6GuehXN406%2Fuy8%2BlboWrpBQnfOFV6oPk0bxAhcM57la70MLIdZ%2BROhD8%2F5eFp%2BlBQAkFdOlELMWSZzkgN4oeBZ1xHYhZgfyFUUv5LVW3MTsVrcAwlrQl48ge7YpB0iddOiEDVvwWinmb7PZDHAXnWa2V6U3XRzDfg42qzUonaSTdYn4ZkRloSzqbgf%2Bz4P5JJ9FlXZgZ2NXO4F3sb8sW6%2Bq4LkGMDwLbRvkLfBSBREFxHVOevMMQC87fy6PmpBx6pzmSJzXamysMhwpnG5rKhk6Em0QowEEhyvnrSoLpLyZX3EwpJogKEmOl7LxSlNQbIjZ5md8qJg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/wandb-summary.json?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=iYCyYkFRl%2Fkr6GuehXN406%2Fuy8%2BlboWrpBQnfOFV6oPk0bxAhcM57la70MLIdZ%2BROhD8%2F5eFp%2BlBQAkFdOlELMWSZzkgN4oeBZ1xHYhZgfyFUUv5LVW3MTsVrcAwlrQl48ge7YpB0iddOiEDVvwWinmb7PZDHAXnWa2V6U3XRzDfg42qzUonaSTdYn4ZkRloSzqbgf%2Bz4P5JJ9FlXZgZ2NXO4F3sb8sW6%2Bq4LkGMDwLbRvkLfBSBREFxHVOevMMQC87fy6PmpBx6pzmSJzXamysMhwpnG5rKhk6Em0QowEEhyvnrSoLpLyZX3EwpJogKEmOl7LxSlNQbIjZ5md8qJg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f08334fa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:51,847 ERROR   Thread-21 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:17:51,847 ERROR   Thread-21 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:52,231 ERROR   Thread-22 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/config.yaml?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=H6amYcwHvij6ZBShcIOmMB4ccq4RXMHCp%2FsY9QQrhy%2FlhtPOVpFzTpBO5b99eL62As1%2BimvhKnzk8Vr2V%2FQJldGdNW1mu0%2BSUGZiN3trhuG5E916Ks8L0BtXWWFwF0rCLT7YqPvM1DxH%2FS9Pt9OVRZxPI57mMnIpk6ND0fLLBjSb%2BngcGtWlNsOhA5%2FfFoFpnCDqnFS9s6HoPO7H70G1nDtPqXfuzXXO2ZQ665Sg5Z3Zq5a%2BWuoDd7Ym2XPJD%2BKaYTWiis6osl6TWZPfVrjOUs4e1HWYF5P5Z2WJMNBVclzu2yMu%2FrM8ctYyaXit8ywUCD6VftuHeQ0e71OMYdA0HQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/config.yaml?Expires=1669202238&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=H6amYcwHvij6ZBShcIOmMB4ccq4RXMHCp%2FsY9QQrhy%2FlhtPOVpFzTpBO5b99eL62As1%2BimvhKnzk8Vr2V%2FQJldGdNW1mu0%2BSUGZiN3trhuG5E916Ks8L0BtXWWFwF0rCLT7YqPvM1DxH%2FS9Pt9OVRZxPI57mMnIpk6ND0fLLBjSb%2BngcGtWlNsOhA5%2FfFoFpnCDqnFS9s6HoPO7H70G1nDtPqXfuzXXO2ZQ665Sg5Z3Zq5a%2BWuoDd7Ym2XPJD%2BKaYTWiis6osl6TWZPfVrjOUs4e1HWYF5P5Z2WJMNBVclzu2yMu%2FrM8ctYyaXit8ywUCD6VftuHeQ0e71OMYdA0HQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f0825c520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:52,231 ERROR   Thread-22 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:17:52,231 ERROR   Thread-22 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:54,036 ERROR   Thread-20 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=XRIPYmr530ARZ%2FvBYkXAOBG4dFq9NZeVIrfmKyU9AwiHqgftZy4%2BmmRcQMi9d8vgN9iMxKduyPnJ0dmbP6%2FV4Zbmkk5bil%2F%2BTsZByPzK%2Fbcy3mS0M%2FhzmewozRvPB8vsaYOIKTSM8EfQD3srcuiJ%2FY6ZnYnfkFNt5h1ricxTwCTd%2FBcPoQfmDvQUScEBCMidQJ9NlNr5wI%2BPWobY6p83gaXuiuxzClWRkUHoEpPZkSkJkMmRxcMomcahDJOrebXfXLHI8ixY3vj%2B6qEHDZn5zGXr9TWq2xQW5qRGg4XoA%2BntWWk%2FcwQMytYllbqli7sYMj9CBmpff9FAc3WX%2FZotvA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/wandb-metadata.json?Expires=1669202225&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=XRIPYmr530ARZ%2FvBYkXAOBG4dFq9NZeVIrfmKyU9AwiHqgftZy4%2BmmRcQMi9d8vgN9iMxKduyPnJ0dmbP6%2FV4Zbmkk5bil%2F%2BTsZByPzK%2Fbcy3mS0M%2FhzmewozRvPB8vsaYOIKTSM8EfQD3srcuiJ%2FY6ZnYnfkFNt5h1ricxTwCTd%2FBcPoQfmDvQUScEBCMidQJ9NlNr5wI%2BPWobY6p83gaXuiuxzClWRkUHoEpPZkSkJkMmRxcMomcahDJOrebXfXLHI8ixY3vj%2B6qEHDZn5zGXr9TWq2xQW5qRGg4XoA%2BntWWk%2FcwQMytYllbqli7sYMj9CBmpff9FAc3WX%2FZotvA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f083eeca0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:54,037 ERROR   Thread-20 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2654'}
2022-11-22 19:17:54,038 ERROR   Thread-20 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:56,650 ERROR   Thread-25 :37627 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/conda-environment.yaml?Expires=1669202242&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=FR0ph17H34SZtLAp3XnK8NVTiqz8bn5q%2BrAVJvTYVzl5wxUX8Os19ox0lrl4mqIaOwFsEBcr8kKda6aW2ospktQ6AbCYV5lzE%2BL7zTnJ8paIzqTD8n0ZQPNkYr1br3F2UCK61nbb9aa9MUa%2BCQDrd4%2FHjXXEe%2B4yVW3JvYK%2Fat0bJ6NgtRrg15lx79JTwljAaJqrFX2FVvv2jm5Zxizf%2B5hpBXax7RWFoqMXSYODQNbG%2FsH%2BqiyaeaytB4CdJn1jT376pmpwvh18SmMJWbSFxrCpNWpOAYNgNY0x3FmPQ5s292hNmU86IYh5rhemGhCOB1qsh%2FchSHSGD5ESz2n80g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vquv0w3/conda-environment.yaml?Expires=1669202242&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=FR0ph17H34SZtLAp3XnK8NVTiqz8bn5q%2BrAVJvTYVzl5wxUX8Os19ox0lrl4mqIaOwFsEBcr8kKda6aW2ospktQ6AbCYV5lzE%2BL7zTnJ8paIzqTD8n0ZQPNkYr1br3F2UCK61nbb9aa9MUa%2BCQDrd4%2FHjXXEe%2B4yVW3JvYK%2Fat0bJ6NgtRrg15lx79JTwljAaJqrFX2FVvv2jm5Zxizf%2B5hpBXax7RWFoqMXSYODQNbG%2FsH%2BqiyaeaytB4CdJn1jT376pmpwvh18SmMJWbSFxrCpNWpOAYNgNY0x3FmPQ5s292hNmU86IYh5rhemGhCOB1qsh%2FchSHSGD5ESz2n80g%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9f083b8340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:56,650 ERROR   Thread-25 :37627 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:17:56,650 ERROR   Thread-25 :37627 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:59,295 INFO    Thread-21 :37627 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/wandb-summary.json
2022-11-22 19:17:59,309 INFO    Thread-24 :37627 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/requirements.txt
2022-11-22 19:17:59,319 INFO    Thread-22 :37627 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/config.yaml
2022-11-22 19:17:59,435 INFO    Thread-23 :37627 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/output.log
2022-11-22 19:18:01,857 INFO    Thread-25 :37627 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191619-2vquv0w3/files/conda-environment.yaml
2022-11-22 19:18:04,305 INFO    Thread-20 :37627 [upload_job.py:push():143] Uploaded file /tmp/tmp4ly8pwifwandb/2oetruvu-wandb-metadata.json
2022-11-22 19:18:04,506 INFO    Thread-16 :37627 [sender.py:transition_state():463] send defer: 9
