2022-11-22 21:34:16,394 INFO    StreamThr :54706 [internal.py:wandb_internal():88] W&B internal server running at pid: 54706, started at: 2022-11-22 21:34:16.393933
2022-11-22 21:34:16,399 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: status
2022-11-22 21:34:16,399 DEBUG   SenderThread:54706 [sender.py:send_request():317] send_request: status
2022-11-22 21:34:16,400 INFO    WriterThread:54706 [datastore.py:open_for_write():75] open: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/run-26ta6tdb.wandb
2022-11-22 21:34:16,401 DEBUG   SenderThread:54706 [sender.py:send():303] send: header
2022-11-22 21:34:16,401 DEBUG   SenderThread:54706 [sender.py:send():303] send: run
2022-11-22 21:34:16,420 INFO    SenderThread:54706 [sender.py:_maybe_setup_resume():593] checking resume status for None/YOLOR/26ta6tdb
2022-11-22 21:34:18,239 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: check_version
2022-11-22 21:34:18,240 INFO    SenderThread:54706 [dir_watcher.py:__init__():216] watching files in: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files
2022-11-22 21:34:18,240 INFO    SenderThread:54706 [sender.py:_start_run_threads():928] run started: 26ta6tdb with start time 1669124056.390707
2022-11-22 21:34:18,240 DEBUG   SenderThread:54706 [sender.py:send():303] send: summary
2022-11-22 21:34:18,240 INFO    SenderThread:54706 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 21:34:18,241 DEBUG   SenderThread:54706 [sender.py:send_request():317] send_request: check_version
2022-11-22 21:34:19,244 INFO    Thread-17 :54706 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/wandb-summary.json
2022-11-22 21:34:21,026 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: run_start
2022-11-22 21:34:21,029 DEBUG   HandlerThread:54706 [system_info.py:__init__():31] System info init
2022-11-22 21:34:21,029 DEBUG   HandlerThread:54706 [system_info.py:__init__():46] System info init done
2022-11-22 21:34:21,029 INFO    HandlerThread:54706 [system_monitor.py:start():150] Starting system monitor
2022-11-22 21:34:21,029 INFO    SystemMonitor:54706 [system_monitor.py:_start():116] Starting system asset monitoring threads
2022-11-22 21:34:21,029 INFO    HandlerThread:54706 [system_monitor.py:probe():168] Collecting system info
2022-11-22 21:34:21,030 INFO    SystemMonitor:54706 [interfaces.py:start():168] Started cpu
2022-11-22 21:34:21,032 INFO    SystemMonitor:54706 [interfaces.py:start():168] Started disk
2022-11-22 21:34:21,032 INFO    SystemMonitor:54706 [interfaces.py:start():168] Started gpu
2022-11-22 21:34:21,033 INFO    SystemMonitor:54706 [interfaces.py:start():168] Started memory
2022-11-22 21:34:21,033 INFO    SystemMonitor:54706 [interfaces.py:start():168] Started network
2022-11-22 21:34:21,097 DEBUG   HandlerThread:54706 [system_info.py:probe():195] Probing system
2022-11-22 21:34:21,105 DEBUG   HandlerThread:54706 [git.py:repo():40] git repository is invalid
2022-11-22 21:34:21,106 DEBUG   HandlerThread:54706 [system_info.py:probe():241] Probing system done
2022-11-22 21:34:21,106 DEBUG   HandlerThread:54706 [system_monitor.py:probe():177] {'os': 'Linux-5.15.0-53-generic-x86_64-with-glibc2.17', 'python': '3.8.13', 'heartbeatAt': '2022-11-22T13:34:21.097460', 'startedAt': '2022-11-22T13:34:16.383521', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/rp/DeepLearning/yolov7-main/train.py', 'codePath': 'train.py', 'host': 'rp', 'username': 'rp', 'executable': '/home/rp/Softwares/anaconda3/envs/dyh/bin/python', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3004.8183125, 'min': 800.0, 'max': 4800.0}, 'cpu_freq_per_core': [{'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 3145.285, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 3036.738, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}], 'disk': {'total': 937.3305015563965, 'used': 300.9005317687988}, 'gpu': 'NVIDIA GeForce RTX 3080', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10497294336}], 'memory': {'total': 31.272598266601562}}
2022-11-22 21:34:21,106 INFO    HandlerThread:54706 [system_monitor.py:probe():178] Finished collecting system info
2022-11-22 21:34:21,107 INFO    HandlerThread:54706 [system_monitor.py:probe():181] Publishing system info
2022-11-22 21:34:21,107 DEBUG   HandlerThread:54706 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2022-11-22 21:34:21,110 DEBUG   HandlerThread:54706 [system_info.py:_save_pip():67] Saving pip packages done
2022-11-22 21:34:21,110 DEBUG   HandlerThread:54706 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2022-11-22 21:34:21,241 INFO    Thread-17 :54706 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/requirements.txt
2022-11-22 21:34:21,242 INFO    Thread-17 :54706 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/conda-environment.yaml
2022-11-22 21:34:23,505 DEBUG   HandlerThread:54706 [system_info.py:_save_conda():86] Saving conda packages done
2022-11-22 21:34:23,513 INFO    HandlerThread:54706 [system_monitor.py:probe():183] Finished publishing system info
2022-11-22 21:34:23,550 DEBUG   SenderThread:54706 [sender.py:send():303] send: files
2022-11-22 21:34:23,550 INFO    SenderThread:54706 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2022-11-22 21:34:23,561 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: stop_status
2022-11-22 21:34:23,561 DEBUG   SenderThread:54706 [sender.py:send_request():317] send_request: stop_status
2022-11-22 21:34:24,242 INFO    Thread-17 :54706 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/conda-environment.yaml
2022-11-22 21:34:24,243 INFO    Thread-17 :54706 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/wandb-metadata.json
2022-11-22 21:34:25,206 DEBUG   SenderThread:54706 [sender.py:send():303] send: telemetry
2022-11-22 21:34:25,206 DEBUG   SenderThread:54706 [sender.py:send():303] send: telemetry
2022-11-22 21:34:25,206 DEBUG   SenderThread:54706 [sender.py:send():303] send: config
2022-11-22 21:34:25,207 DEBUG   SenderThread:54706 [sender.py:send():303] send: config
2022-11-22 21:34:25,211 DEBUG   SenderThread:54706 [sender.py:send():303] send: exit
2022-11-22 21:34:25,211 INFO    SenderThread:54706 [sender.py:send_exit():442] handling exit code: 0
2022-11-22 21:34:25,211 INFO    SenderThread:54706 [sender.py:send_exit():444] handling runtime: 3
2022-11-22 21:34:25,216 INFO    SenderThread:54706 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 21:34:25,217 INFO    SenderThread:54706 [sender.py:send_exit():450] send defer
2022-11-22 21:34:25,217 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: defer
2022-11-22 21:34:25,218 INFO    HandlerThread:54706 [handler.py:handle_request_defer():162] handle defer: 0
2022-11-22 21:34:25,218 DEBUG   SenderThread:54706 [sender.py:send_request():317] send_request: defer
2022-11-22 21:34:25,218 INFO    SenderThread:54706 [sender.py:send_request_defer():459] handle sender defer: 0
2022-11-22 21:34:25,218 INFO    SenderThread:54706 [sender.py:transition_state():463] send defer: 1
2022-11-22 21:34:25,218 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: defer
2022-11-22 21:34:25,219 INFO    HandlerThread:54706 [handler.py:handle_request_defer():162] handle defer: 1
2022-11-22 21:34:25,219 INFO    HandlerThread:54706 [system_monitor.py:finish():160] Stopping system monitor
2022-11-22 21:34:25,219 DEBUG   SystemMonitor:54706 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2022-11-22 21:34:25,220 DEBUG   SystemMonitor:54706 [system_monitor.py:_start():137] Finished system metrics aggregation loop
2022-11-22 21:34:25,220 DEBUG   SystemMonitor:54706 [system_monitor.py:_start():141] Publishing last batch of metrics
2022-11-22 21:34:25,221 INFO    HandlerThread:54706 [interfaces.py:finish():173] Joined cpu
2022-11-22 21:34:25,221 INFO    HandlerThread:54706 [interfaces.py:finish():173] Joined disk
2022-11-22 21:34:25,243 INFO    Thread-17 :54706 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/wandb-summary.json
2022-11-22 21:34:25,243 INFO    Thread-17 :54706 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/output.log
2022-11-22 21:34:25,265 INFO    HandlerThread:54706 [interfaces.py:finish():173] Joined gpu
2022-11-22 21:34:25,265 INFO    HandlerThread:54706 [interfaces.py:finish():173] Joined memory
2022-11-22 21:34:25,265 INFO    HandlerThread:54706 [interfaces.py:finish():173] Joined network
2022-11-22 21:34:25,265 DEBUG   SenderThread:54706 [sender.py:send_request():317] send_request: defer
2022-11-22 21:34:25,265 INFO    SenderThread:54706 [sender.py:send_request_defer():459] handle sender defer: 1
2022-11-22 21:34:25,265 INFO    SenderThread:54706 [sender.py:transition_state():463] send defer: 2
2022-11-22 21:34:25,266 DEBUG   SenderThread:54706 [sender.py:send():303] send: stats
2022-11-22 21:34:25,266 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: defer
2022-11-22 21:34:25,266 INFO    HandlerThread:54706 [handler.py:handle_request_defer():162] handle defer: 2
2022-11-22 21:34:25,266 DEBUG   SenderThread:54706 [sender.py:send_request():317] send_request: defer
2022-11-22 21:34:25,266 INFO    SenderThread:54706 [sender.py:send_request_defer():459] handle sender defer: 2
2022-11-22 21:34:25,266 INFO    SenderThread:54706 [sender.py:transition_state():463] send defer: 3
2022-11-22 21:34:25,267 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: defer
2022-11-22 21:34:25,267 INFO    HandlerThread:54706 [handler.py:handle_request_defer():162] handle defer: 3
2022-11-22 21:34:25,267 DEBUG   SenderThread:54706 [sender.py:send_request():317] send_request: defer
2022-11-22 21:34:25,267 INFO    SenderThread:54706 [sender.py:send_request_defer():459] handle sender defer: 3
2022-11-22 21:34:25,267 INFO    SenderThread:54706 [sender.py:transition_state():463] send defer: 4
2022-11-22 21:34:25,267 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: defer
2022-11-22 21:34:25,267 INFO    HandlerThread:54706 [handler.py:handle_request_defer():162] handle defer: 4
2022-11-22 21:34:25,268 DEBUG   SenderThread:54706 [sender.py:send():303] send: summary
2022-11-22 21:34:25,268 INFO    SenderThread:54706 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 21:34:25,268 DEBUG   SenderThread:54706 [sender.py:send_request():317] send_request: defer
2022-11-22 21:34:25,268 INFO    SenderThread:54706 [sender.py:send_request_defer():459] handle sender defer: 4
2022-11-22 21:34:25,268 INFO    SenderThread:54706 [sender.py:transition_state():463] send defer: 5
2022-11-22 21:34:25,268 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: defer
2022-11-22 21:34:25,268 INFO    HandlerThread:54706 [handler.py:handle_request_defer():162] handle defer: 5
2022-11-22 21:34:25,269 DEBUG   SenderThread:54706 [sender.py:send_request():317] send_request: defer
2022-11-22 21:34:25,269 INFO    SenderThread:54706 [sender.py:send_request_defer():459] handle sender defer: 5
2022-11-22 21:34:25,540 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: poll_exit
2022-11-22 21:34:26,245 INFO    Thread-17 :54706 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/wandb-summary.json
2022-11-22 21:34:27,289 INFO    Thread-17 :54706 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/output.log
2022-11-22 21:34:30,544 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 21:34:35,550 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 21:34:40,218 ERROR   Thread-20 :54706 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/26ta6tdb/wandb-metadata.json?Expires=1669210464&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fwhwX8kJq6SfsA6GfOaNu7NIHapTHwHYAgnAksSDzRpq2OaOWj6PhXSEbFVsJzVmHpjfAjvpbxKWZYEOAB8lLwBIsXKX4QSpwqUGvbdMA1gJ1fd1tsUdUJSACyiR7oHYYsbBoBWJ2KrCGs3RHAjOC53tMP206hUp%2B%2BDcGWGZTZVmMWDeCAHDciqV9XVTHs0aIGD%2F4FkRq8XbLZMqgXvppg34owTJ1ygTwpJnBx92nmD4S5TmrGtaROU5olD%2BYnD4TBVdkpd%2B76EoJqiaoTs3IEe841%2FzY0DKshanx1847hV3ync1I0AdOP93QTOk40l2d%2FJ0Ryzn44K8P0B1vXECPg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/26ta6tdb/wandb-metadata.json?Expires=1669210464&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fwhwX8kJq6SfsA6GfOaNu7NIHapTHwHYAgnAksSDzRpq2OaOWj6PhXSEbFVsJzVmHpjfAjvpbxKWZYEOAB8lLwBIsXKX4QSpwqUGvbdMA1gJ1fd1tsUdUJSACyiR7oHYYsbBoBWJ2KrCGs3RHAjOC53tMP206hUp%2B%2BDcGWGZTZVmMWDeCAHDciqV9XVTHs0aIGD%2F4FkRq8XbLZMqgXvppg34owTJ1ygTwpJnBx92nmD4S5TmrGtaROU5olD%2BYnD4TBVdkpd%2B76EoJqiaoTs3IEe841%2FzY0DKshanx1847hV3ync1I0AdOP93QTOk40l2d%2FJ0Ryzn44K8P0B1vXECPg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48a46016a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 21:34:40,219 ERROR   Thread-20 :54706 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2654'}
2022-11-22 21:34:40,219 ERROR   Thread-20 :54706 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 21:34:40,552 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 21:34:45,556 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 21:34:50,559 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 21:34:51,486 ERROR   Thread-20 :54706 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/26ta6tdb/wandb-metadata.json?Expires=1669210464&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fwhwX8kJq6SfsA6GfOaNu7NIHapTHwHYAgnAksSDzRpq2OaOWj6PhXSEbFVsJzVmHpjfAjvpbxKWZYEOAB8lLwBIsXKX4QSpwqUGvbdMA1gJ1fd1tsUdUJSACyiR7oHYYsbBoBWJ2KrCGs3RHAjOC53tMP206hUp%2B%2BDcGWGZTZVmMWDeCAHDciqV9XVTHs0aIGD%2F4FkRq8XbLZMqgXvppg34owTJ1ygTwpJnBx92nmD4S5TmrGtaROU5olD%2BYnD4TBVdkpd%2B76EoJqiaoTs3IEe841%2FzY0DKshanx1847hV3ync1I0AdOP93QTOk40l2d%2FJ0Ryzn44K8P0B1vXECPg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/26ta6tdb/wandb-metadata.json?Expires=1669210464&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fwhwX8kJq6SfsA6GfOaNu7NIHapTHwHYAgnAksSDzRpq2OaOWj6PhXSEbFVsJzVmHpjfAjvpbxKWZYEOAB8lLwBIsXKX4QSpwqUGvbdMA1gJ1fd1tsUdUJSACyiR7oHYYsbBoBWJ2KrCGs3RHAjOC53tMP206hUp%2B%2BDcGWGZTZVmMWDeCAHDciqV9XVTHs0aIGD%2F4FkRq8XbLZMqgXvppg34owTJ1ygTwpJnBx92nmD4S5TmrGtaROU5olD%2BYnD4TBVdkpd%2B76EoJqiaoTs3IEe841%2FzY0DKshanx1847hV3ync1I0AdOP93QTOk40l2d%2FJ0Ryzn44K8P0B1vXECPg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48a44469d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 21:34:51,486 ERROR   Thread-20 :54706 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2654'}
2022-11-22 21:34:51,486 ERROR   Thread-20 :54706 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 21:34:55,563 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 21:35:00,566 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 21:35:03,747 ERROR   Thread-20 :54706 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/26ta6tdb/wandb-metadata.json?Expires=1669210464&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fwhwX8kJq6SfsA6GfOaNu7NIHapTHwHYAgnAksSDzRpq2OaOWj6PhXSEbFVsJzVmHpjfAjvpbxKWZYEOAB8lLwBIsXKX4QSpwqUGvbdMA1gJ1fd1tsUdUJSACyiR7oHYYsbBoBWJ2KrCGs3RHAjOC53tMP206hUp%2B%2BDcGWGZTZVmMWDeCAHDciqV9XVTHs0aIGD%2F4FkRq8XbLZMqgXvppg34owTJ1ygTwpJnBx92nmD4S5TmrGtaROU5olD%2BYnD4TBVdkpd%2B76EoJqiaoTs3IEe841%2FzY0DKshanx1847hV3ync1I0AdOP93QTOk40l2d%2FJ0Ryzn44K8P0B1vXECPg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/26ta6tdb/wandb-metadata.json?Expires=1669210464&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fwhwX8kJq6SfsA6GfOaNu7NIHapTHwHYAgnAksSDzRpq2OaOWj6PhXSEbFVsJzVmHpjfAjvpbxKWZYEOAB8lLwBIsXKX4QSpwqUGvbdMA1gJ1fd1tsUdUJSACyiR7oHYYsbBoBWJ2KrCGs3RHAjOC53tMP206hUp%2B%2BDcGWGZTZVmMWDeCAHDciqV9XVTHs0aIGD%2F4FkRq8XbLZMqgXvppg34owTJ1ygTwpJnBx92nmD4S5TmrGtaROU5olD%2BYnD4TBVdkpd%2B76EoJqiaoTs3IEe841%2FzY0DKshanx1847hV3ync1I0AdOP93QTOk40l2d%2FJ0Ryzn44K8P0B1vXECPg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48a4587cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 21:35:03,748 ERROR   Thread-20 :54706 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2654'}
2022-11-22 21:35:03,748 ERROR   Thread-20 :54706 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 21:35:03,748 ERROR   Thread-20 :54706 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f48a4587cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/26ta6tdb/wandb-metadata.json?Expires=1669210464&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fwhwX8kJq6SfsA6GfOaNu7NIHapTHwHYAgnAksSDzRpq2OaOWj6PhXSEbFVsJzVmHpjfAjvpbxKWZYEOAB8lLwBIsXKX4QSpwqUGvbdMA1gJ1fd1tsUdUJSACyiR7oHYYsbBoBWJ2KrCGs3RHAjOC53tMP206hUp%2B%2BDcGWGZTZVmMWDeCAHDciqV9XVTHs0aIGD%2F4FkRq8XbLZMqgXvppg34owTJ1ygTwpJnBx92nmD4S5TmrGtaROU5olD%2BYnD4TBVdkpd%2B76EoJqiaoTs3IEe841%2FzY0DKshanx1847hV3ync1I0AdOP93QTOk40l2d%2FJ0Ryzn44K8P0B1vXECPg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48a4587cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1923, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/requests/api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/26ta6tdb/wandb-metadata.json?Expires=1669210464&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=fwhwX8kJq6SfsA6GfOaNu7NIHapTHwHYAgnAksSDzRpq2OaOWj6PhXSEbFVsJzVmHpjfAjvpbxKWZYEOAB8lLwBIsXKX4QSpwqUGvbdMA1gJ1fd1tsUdUJSACyiR7oHYYsbBoBWJ2KrCGs3RHAjOC53tMP206hUp%2B%2BDcGWGZTZVmMWDeCAHDciqV9XVTHs0aIGD%2F4FkRq8XbLZMqgXvppg34owTJ1ygTwpJnBx92nmD4S5TmrGtaROU5olD%2BYnD4TBVdkpd%2B76EoJqiaoTs3IEe841%2FzY0DKshanx1847hV3ync1I0AdOP93QTOk40l2d%2FJ0Ryzn44K8P0B1vXECPg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48a4587cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1950, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1923, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/requests/api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/rp/Softwares/anaconda3/envs/dyh/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2022-11-22 21:35:05,571 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 21:35:09,014 INFO    SenderThread:54706 [sender.py:transition_state():463] send defer: 6
2022-11-22 21:35:09,014 DEBUG   SenderThread:54706 [sender.py:send_request():317] send_request: poll_exit
2022-11-22 21:35:09,015 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: defer
2022-11-22 21:35:09,015 INFO    HandlerThread:54706 [handler.py:handle_request_defer():162] handle defer: 6
2022-11-22 21:35:09,015 DEBUG   SenderThread:54706 [sender.py:send_request():317] send_request: defer
2022-11-22 21:35:09,015 INFO    SenderThread:54706 [sender.py:send_request_defer():459] handle sender defer: 6
2022-11-22 21:35:09,340 INFO    Thread-17 :54706 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/config.yaml
2022-11-22 21:35:09,380 INFO    SenderThread:54706 [sender.py:transition_state():463] send defer: 7
2022-11-22 21:35:09,381 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: defer
2022-11-22 21:35:09,382 INFO    HandlerThread:54706 [handler.py:handle_request_defer():162] handle defer: 7
2022-11-22 21:35:09,383 DEBUG   SenderThread:54706 [sender.py:send_request():317] send_request: defer
2022-11-22 21:35:09,383 INFO    SenderThread:54706 [sender.py:send_request_defer():459] handle sender defer: 7
2022-11-22 21:35:09,384 INFO    SenderThread:54706 [dir_watcher.py:finish():362] shutting down directory watcher
2022-11-22 21:35:10,341 INFO    Thread-17 :54706 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/output.log
2022-11-22 21:35:10,345 INFO    SenderThread:54706 [dir_watcher.py:finish():392] scan: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files
2022-11-22 21:35:10,346 INFO    SenderThread:54706 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/wandb-summary.json wandb-summary.json
2022-11-22 21:35:10,347 INFO    SenderThread:54706 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/config.yaml config.yaml
2022-11-22 21:35:10,347 INFO    SenderThread:54706 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/output.log output.log
2022-11-22 21:35:10,348 INFO    SenderThread:54706 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/requirements.txt requirements.txt
2022-11-22 21:35:10,356 INFO    SenderThread:54706 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/conda-environment.yaml conda-environment.yaml
2022-11-22 21:35:10,357 INFO    SenderThread:54706 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/wandb-metadata.json wandb-metadata.json
2022-11-22 21:35:10,357 INFO    SenderThread:54706 [sender.py:transition_state():463] send defer: 8
2022-11-22 21:35:10,394 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: defer
2022-11-22 21:35:10,394 INFO    HandlerThread:54706 [handler.py:handle_request_defer():162] handle defer: 8
2022-11-22 21:35:10,401 DEBUG   SenderThread:54706 [sender.py:send_request():317] send_request: defer
2022-11-22 21:35:10,405 INFO    SenderThread:54706 [sender.py:send_request_defer():459] handle sender defer: 8
2022-11-22 21:35:10,405 INFO    SenderThread:54706 [file_pusher.py:finish():168] shutting down file pusher
2022-11-22 21:35:10,574 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 21:35:15,579 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 21:35:20,581 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 21:35:25,585 DEBUG   HandlerThread:54706 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 21:35:37,480 WARNING StreamThr :54706 [internal.py:is_dead():385] Internal process exiting, parent pid 54676 disappeared
2022-11-22 21:35:37,481 ERROR   StreamThr :54706 [internal.py:wandb_internal():147] Internal process shutdown.
2022-11-22 21:35:37,600 INFO    HandlerThread:54706 [handler.py:finish():814] shutting down handler
2022-11-22 21:35:38,311 INFO    WriterThread:54706 [datastore.py:close():279] close: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/run-26ta6tdb.wandb
2022-11-22 21:35:38,420 INFO    SenderThread:54706 [sender.py:finish():1331] shutting down sender
2022-11-22 21:35:38,420 INFO    SenderThread:54706 [file_pusher.py:finish():168] shutting down file pusher
2022-11-22 21:35:38,420 INFO    SenderThread:54706 [file_pusher.py:join():173] waiting for file pusher
2022-11-22 21:37:20,595 INFO    Thread-20 :54706 [upload_job.py:push():143] Uploaded file /tmp/tmpy1vm088_wandb/1i1fr8wu-wandb-metadata.json
2022-11-22 21:37:22,645 INFO    Thread-24 :54706 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/requirements.txt
2022-11-22 21:37:22,659 INFO    Thread-22 :54706 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/config.yaml
2022-11-22 21:37:22,660 INFO    Thread-21 :54706 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/wandb-summary.json
2022-11-22 21:37:22,660 INFO    Thread-23 :54706 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/output.log
2022-11-22 21:37:22,726 INFO    Thread-25 :54706 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_213416-26ta6tdb/files/conda-environment.yaml
2022-11-22 21:37:22,926 INFO    Thread-16 :54706 [sender.py:transition_state():463] send defer: 9
